package gg.aquatic.klocale.impl.paper

import net.kyori.adventure.text.Component
import net.kyori.adventure.text.TextComponent
import net.kyori.adventure.text.event.ClickEvent
import net.kyori.adventure.text.event.HoverEvent
import net.kyori.adventure.text.format.Style
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer
import org.bukkit.command.CommandSender
import kotlinx.coroutines.runBlocking
import kotlin.math.max
import kotlin.math.min

val PLACEHOLDER_REGEX = Regex("%([^%]+)%")
private const val PAGE_CLICK_PREFIX = "__aq_page__:"
private const val VISIBILITY_INSERT_PREFIX = "__aq_visible__:"

/**
 * Finds all unique placeholders within this Component and its children.
 * A placeholder is defined by a specific pattern, typically surrounded by
 * specific symbols (e.g., `%placeholder%`). The search is recursive,
 * traversing all nested child components.
 *
 * @return a set of strings representing unique placeholders found within the component hierarchy.
 */
fun Component.findPlaceholders(): Set<String> {
    val result = mutableSetOf<String>()

    fun recurse(comp: Component) {
        comp.style().insertion()?.let { insertion ->
            PLACEHOLDER_REGEX.findAll(insertion).forEach { match ->
                result.add(match.groupValues[1])
            }
        }
        comp.style().clickEvent()?.let { click ->
            val clickValue = click.payloadTextValue() ?: return@let
            PLACEHOLDER_REGEX.findAll(clickValue).forEach { match ->
                result.add(match.groupValues[1])
            }
        }
        comp.style().hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    recurse(hoverComp)
                }
            }
        }
        if (comp is TextComponent) {
            val text = comp.content()
            PLACEHOLDER_REGEX.findAll(text).forEach { match ->
                result.add(match.groupValues[1]) // only the inside of %...%
            }
        }
        for (child in comp.children()) {
            recurse(child)
        }
    }

    recurse(this)
    return result
}

/**
 * Replaces placeholders within a Component object and its children using the provided updater function.
 * The method applies transformations recursively to text content, insertion text, and hover events.
 *
 * @param updater a function that takes a string and returns an updated string. This function is applied to
 *                text content and insertion text within the component's structure.
 * @return a new Component object where all placeholders have been replaced as per the updater function.
 */
fun Component.replacePlaceholders(updater: (String) -> String): Component {
    fun recurse(comp: Component): Component {
        val style = comp.style()
        var newStyle = style

        // Handle hover event if present
        style.hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    val replacedHover = recurse(hoverComp)
                    newStyle = newStyle.hoverEvent(HoverEvent.showText(replacedHover))
                }
            }
        }

        style.clickEvent()?.let { click ->
            click.updated(updater)?.let { updated ->
                newStyle = newStyle.clickEvent(updated)
            }
        }

        // Handle insertion text (plain string)
        style.insertion()?.let { insertion ->
            val newInsertion = updater(insertion)
            newStyle = newStyle.insertion(newInsertion)
        }

        var newComponent = if (comp is TextComponent) {
            val newText = updater(comp.content())
            val rebuilt = Component.text(newText).style(newStyle)
            rebuilt
        } else {
            val rebuilt: Component = comp.style(newStyle)
            rebuilt
        }
        for (child in comp.children()) {
            newComponent = newComponent.append(recurse(child))
        }
        return newComponent
    }
    return recurse(this)
}

/**
 * Replaces parts of this Component with other Components based on a mapping.
 *
 * The method traverses the current Component structure recursively, searching for
 * string keys specified in the provided map. When a key is found, it is replaced
 * with the corresponding Component generated by the map value function. The Style
 * of the replaced parts is preserved.
 *
 * @param map A map where keys are strings to be replaced and values are functions
 *            that return the replacement Components.
 * @return A new Component with the specified replacements applied.
 */
fun Component.replaceWith(map: Map<String, () -> Component>): Component {
    fun recurseSplit(mapLeft: Map<String, () -> Component>, str: String, style: Style): Component {
        var component = Component.text()
        val left = mapLeft.toMutableMap()

        var found = false
        mapLeft.forEach { (key, value) ->
            if (str.contains(key)) {
                left -= key

                val split = str.split(key)

                for ((index, string) in split.withIndex()) {
                    component = component.append(recurseSplit(left.toMutableMap(), string, style))
                    if (index < split.size - 1) {
                        component = component.append(value)
                    }
                }
                found = true
            }
        }
        if (!found) {
            component = component.append(Component.text(str, style))
        }
        return component.build()
    }

    fun recurse(comp: Component): Component {
        val style = comp.style()
        var newStyle = style

        // Handle hover event if present
        style.hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    val replacedHover = recurse(hoverComp)
                    newStyle = newStyle.hoverEvent(HoverEvent.showText(replacedHover))
                }
            }
        }

        var newComponent = if (comp is TextComponent) {
            recurseSplit(map, comp.content(), newStyle)
        } else {
            val rebuilt: Component = comp.style(newStyle)
            rebuilt
        }
        for (child in comp.children()) {
            newComponent = newComponent.append(recurse(child))
        }
        return newComponent
    }
    return recurse(this)
}

/**
 * Only use when we 100% know that we got predefined placeholders
 */
fun Component.replacePlaceholders(cached: Map<String, String>): Component {
    fun recurse(comp: Component): Component {
        val style = comp.style()
        var newStyle = style

        // Handle hover event if present
        style.hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    val replacedHover = recurse(hoverComp)
                    newStyle = newStyle.hoverEvent(HoverEvent.showText(replacedHover))
                }
            }
        }

        style.clickEvent()?.let { click ->
            val rawValue = click.payloadTextValue() ?: return@let
            var newValue = rawValue
            PLACEHOLDER_REGEX.findAll(newValue).forEach { match ->
                val key = match.groupValues[1]
                newValue = newValue.replace("%$key%", cached[key] ?: key)
            }
            click.updated { newValue }?.let { updated ->
                newStyle = newStyle.clickEvent(updated)
            }
        }

        // Handle insertion text (plain string)
        style.insertion()?.let { insertion ->
            var newInsertion = insertion
            PLACEHOLDER_REGEX.findAll(insertion).forEach { match ->
                val key = match.groupValues[1]
                newInsertion = insertion.replace("%$key%", cached[key] ?: key)
            }
            newStyle = newStyle.insertion(newInsertion)
        }

        var newComponent = if (comp is TextComponent) {
            var newText = comp.content()
            PLACEHOLDER_REGEX.findAll(newText).forEach { match ->
                val key = match.groupValues[1]
                newText = newText.replace("%$key%", cached[key] ?: key)
            }
            val rebuilt = Component.text(newText).style(newStyle)
            rebuilt
        } else {
            val rebuilt: Component = comp.style(newStyle)
            rebuilt
        }
        for (child in comp.children()) {
            newComponent = newComponent.append(recurse(child))
        }
        return newComponent
    }
    return recurse(this)
}

/**
 * Determines if the current component or any of its child components contain placeholders.
 * A placeholder is identified using a predefined regex pattern within the content of a
 * TextComponent or its descendants.
 *
 * @return true if a placeholder is found within the component or its children, otherwise false.
 */
fun Component.containsPlaceholder(): Boolean {
    fun recurse(comp: Component): Boolean {
        if (comp is TextComponent) {
            if (PLACEHOLDER_REGEX.containsMatchIn(comp.content())) {
                return true
            }
        }
        for (child in comp.children()) {
            if (recurse(child)) return true
        }
        return false
    }
    return recurse(this)
}

fun String.hasPlaceholder(): Boolean {
    return PLACEHOLDER_REGEX.containsMatchIn(this)
}

/**
 * Converts a string containing MiniMessage-formatted text or color codes into a `Component` object.
 * The method performs the following:
 * - Replaces legacy color codes (e.g., `&a`) with MiniMessage tags (e.g., `<green>`).
 * - Deserializes the transformed string into a `Component` using MiniMessage.
 * - Provides support for custom tags such as `ccmd` and `locale`, resolved using their respective resolvers.
 *
 * Custom tags:
 * - `ccmd`: Resolves into a tag that executes a console command when clicked.
 * - `locale`: Resolves into a tag that handles translations based on locale identifiers.
 *
 * @return Transformed `Component` with MiniMessage formatting and custom tag support applied.
 */
fun String.toMMComponent(): Component {
    return PaperLocaleBuilder.miniMessage.deserialize(
            this
                .replace("§", "&")
                .replace("&a", "<green>")
                .replace("&c", "<red>")
                .replace("&b", "<aqua>")
                .replace("&e", "<yellow>")
                .replace("&6", "<gold>")
                .replace("&d", "<light_purple>")
                .replace("&f", "<white>")
                .replace("&3", "<dark_aqua>")
                .replace("&9", "<blue>")
                .replace("&7", "<gray>")
                .replace("&8", "<dark_gray>")
                .replace("&4", "<dark_red>")
                .replace("&1", "<dark_blue>")
                .replace("&4", "<dark_red>")
                .replace("&8", "<dark_gray>")
                .replace("&2", "<dark_green>")
                .replace("&5", "<dark_purple>")
                .replace("&0", "<black>")
                .replace("&k", "<obfuscated>")
                .replace("&l", "<bold>")
                .replace("&m", "<strikethrough>")
                .replace("&n", "<underlined>")
                .replace("&o", "<italic>")
                .replace("&r", "<reset>")
        )
}
private val plainSerializer = PlainTextComponentSerializer.plainText()

fun Component.toPlain(): String {
    return plainSerializer.serialize(this)
}

fun Component.toMMString(): String {
    return PaperLocaleBuilder.miniMessage.serialize(this)
}

fun Component.resolvePageCallbacks(
    page: Int,
    totalPages: Int,
    sender: CommandSender,
    message: PaperMessage,
): Component {
    fun targetPage(raw: String): Int? {
        val normalized = raw.removePrefix(PAGE_CLICK_PREFIX).trim().lowercase()
        return when (normalized) {
            "next" -> min(totalPages - 1, page + 1)
            "prev", "previous" -> max(0, page - 1)
            "current" -> page
            else -> normalized.toIntOrNull()?.coerceIn(0, max(totalPages - 1, 0))
        }
    }

    fun recurse(comp: Component): Component {
        val style = comp.style()
        var newStyle = style

        style.hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    newStyle = newStyle.hoverEvent(HoverEvent.showText(recurse(hoverComp)))
                }
            }
        }

        style.clickEvent()?.let { click ->
            val raw = click.payloadTextValue()
            if (raw != null && raw.startsWith(PAGE_CLICK_PREFIX)) {
                val resolvedTarget = targetPage(raw)
                if (resolvedTarget != null) {
                    newStyle = newStyle.clickEvent(
                        ClickEvent.callback {
                            message.send(listOf(sender), resolvedTarget)
                        }
                    )
                }
            }
        }

        var rebuilt = if (comp is TextComponent) {
            Component.text(comp.content()).style(newStyle)
        } else {
            comp.style(newStyle)
        }
        for (child in comp.children()) {
            rebuilt = rebuilt.append(recurse(child))
        }
        return rebuilt
    }

    return recurse(this)
}

fun Component.resolveVisibilityConditions(
    context: MessageContext,
    resolver: (suspend (MessageContext, List<ComponentVisibilityPayload>) -> Boolean)?,
): Component? {
    fun isVisible(raw: String): Boolean {
        val payloads = ComponentVisibilityCodec.decode(raw.removePrefix(VISIBILITY_INSERT_PREFIX).trim())
        if (payloads.isEmpty()) return true
        if (resolver == null) return true
        return runBlocking { resolver(context, payloads) }
    }

    fun recurse(comp: Component): Component? {
        val style = comp.style()
        var newStyle = style

        style.insertion()?.let { insertion ->
            if (insertion.startsWith(VISIBILITY_INSERT_PREFIX)) {
                if (!isVisible(insertion)) {
                    return null
                }
                newStyle = newStyle.insertion(null)
            }
        }

        style.hoverEvent()?.let { hover ->
            if (hover.action() == HoverEvent.Action.SHOW_TEXT) {
                val hoverComp = hover.value() as? Component
                if (hoverComp != null) {
                    val resolvedHover = recurse(hoverComp)
                    newStyle = if (resolvedHover != null) {
                        newStyle.hoverEvent(HoverEvent.showText(resolvedHover))
                    } else {
                        newStyle.hoverEvent(null)
                    }
                }
            }
        }

        var rebuilt = if (comp is TextComponent) {
            Component.text(comp.content()).style(newStyle)
        } else {
            comp.style(newStyle)
        }
        for (child in comp.children()) {
            recurse(child)?.let { rebuilt = rebuilt.append(it) }
        }
        return rebuilt
    }

    return recurse(this)
}

private fun ClickEvent.payloadTextValue(): String? {
    return when (val payload = payload()) {
        is ClickEvent.Payload.Text -> payload.value()
        is ClickEvent.Payload.Int -> payload.integer().toString()
        else -> null
    }
}

private fun ClickEvent.updated(transform: (String) -> String): ClickEvent? {
    return when (action()) {
        ClickEvent.Action.OPEN_URL -> payloadTextValue()?.let(transform)?.let(ClickEvent::openUrl)
        ClickEvent.Action.OPEN_FILE -> payloadTextValue()?.let(transform)?.let(ClickEvent::openFile)
        ClickEvent.Action.RUN_COMMAND -> payloadTextValue()?.let(transform)?.let(ClickEvent::runCommand)
        ClickEvent.Action.SUGGEST_COMMAND -> payloadTextValue()?.let(transform)?.let(ClickEvent::suggestCommand)
        ClickEvent.Action.CHANGE_PAGE -> payloadTextValue()?.let(transform)?.let { value ->
            value.toIntOrNull()?.let(ClickEvent::changePage)
        }
        ClickEvent.Action.COPY_TO_CLIPBOARD -> payloadTextValue()?.let(transform)?.let(ClickEvent::copyToClipboard)
        else -> null
    }
}
